#%RAML 1.0
title: API with Types
mediaType: application/json
uses:
  r: ../ramler.raml 
types:
  Person:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      //:
        (r.codeName): addProps
        type: integer    
