#%RAML 1.0
title: API with Types
mediaType: application/json
uses:
  r: ../ramler.raml 
/anything:
  post:
    body:
      type: object
    responses:
      200:
  get:
      responses:
        200:
          body:
            application/json:
              type: object
            text/csv:
              (r.codeName): getCsv
              type: string
