#%RAML 1.0
title: API with Types
mediaType: application/json
uses:
  g: ../ramler.raml
types:
  Colour:
    type: string
    (g.enum):
      values:
        - name: lightBlue
          description: Colour of the sky
        - name: red
          description: Colour of tomatos
