#%RAML 1.0
title: Generic Type
version: 0.1
mediaType: application/json
baseUri: http://localhost:8080
uses:
  g: ../ramler.raml
annotationTypes:
  notes:  string[]
types:
  Status:
    properties:
      code: integer
      httpStatus: integer
      requestId : string
      text : string
      success : boolean
  ListResult:
    (g.typeVars):
      - T
    properties:
      result:
        (g.typeVar): T
        type: object[]
  Result:
    (g.typeVars): [T]
    properties:
      result:
        (g.typeVar): T
        type: any
  Response:
    (g.typeVars): [T]
    properties:
      data:
        type : Result
        (g.typeArgs):
        - T
      status: Status
      success: boolean
  Animal:
    properties:
      species: string
      numLegs: integer
  Person:
    properties:
      firstName: string
      lastName: 
        type: string
        (notes):
        - N1
        - N2
        - N3
    example:
       {
          firstName: "Donald",
          lastName: "Duck"
       }
  AnimalResponse:
    type: Response
    (g.typeArgs): [Animal]
    properties:
      result:
        type: Animal
       