= Ramler User Manual 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: OPS4J Ramler 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== Purpose

Ramler is a code and documentation generator for RESTful APIs defined by a 
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md[RAML 1.0 specification].

The RESTful API Modeling Language (http://www.raml.org[RAML]) is an open standard for API specifications.

Ramler supports a model-first strategy for designing, implementing and documenting a RESTful API.

Given a RAML specification, Ramler generates Java entity classes and resource interfaces compliant 
with JAX-RS 2.0.

Ramler also generates a link:registry/[static HTML 5 website] with hyperlinked and searchable documentation directly from a RAML specification. 

== Prerequisites

Ramler requires Java 8 and is best used with Maven 3.3.1 or higher. 

The HTML code generator is based on Node.js and npm, but this dependency is encapsulated by the
https://github.com/eirslett/frontend-maven-plugin[`frontend-maven-plugin`]. 

While Maven is not a strict requirement, it is the easiest way to use Ramler. If you prefer other
build tools, you will have to write some glue code to invoke Ramler APIs.

== Credits

* Ramler includes source code for some utility classes from 
https://github.com/mulesoft/raml-for-jax-rs[`raml-for-jax-rs`], but the Java code
generator is a largely independent implementation based on the 
https://github.com/raml-org/raml-java-parser[`raml-java-parser`].

* The HTML generator is a heavily modified copy of https://github.com/lord/slate[Slate], with all 
Ruby dependencies replaced by Java or JavaScript tools or libraries. 
HTML templates are based on http://www.trimou.org[Trimou].

* Markdown content is rendered as HTML using https://github.com/sirthias/pegdown[Pegdown].

= Working with Ramler

== Overview

Using Ramler, a RESTful API can be implemented in the following steps:

* Create a RAML 1.0 model of your API. It is recommended to use the 
https://atom.io/[Atom] editor with the 
http://apiworkbench.com/[API Workbench] plugin for this step. 

* Generate Java entity and API classes from the RAML model, either programmatically, or using the `ramler-maven-plugin`.

* Build a library from the generated classes and include this library in your Java application.

* Manually create JAX-RS resource classes implementing the interfaces generated by Ramler.

* Generate HTML documentation from the RAML model, either programmatically, or using the 
`ramler-maven-plugin`. You can use the default templates and styles or provide your own.

== Using the Maven Plugin

Here is an example of using the `raml-maven-plugin` to generate Java code and a static website:

[source,xml]
----
    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.ops4j.ramler</groupId>
                <artifactId>ramler-maven-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <package>org.ops4j.ramler.samples.registry</package>
                    <model>${basedir}/src/test/resources/raml/registry.raml</model>
                </configuration>
                <executions>
                    <execution>
                        <id>generate</id>
                        <goals>
                            <goal>java</goal>
                            <goal>html</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <doclet>ch.raffael.doclets.pegdown.PegdownDoclet</doclet>
                    <docletArtifact>
                        <groupId>ch.raffael.pegdown-doclet</groupId>
                        <artifactId>pegdown-doclet</artifactId>
                        <version>1.3</version>
                    </docletArtifact>
                    <useStandardDocletOptions>true</useStandardDocletOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>
----

== Limitations

Please note the following limitations when using Ramler:

* RAML 0.8 is not supported. Ramler requires a RAML 1.0 specification.
* Only native RAML types are supported. Ramler cannot handle type definitions based on JSON Schema or
  XML schema.
* Examples in the RAML specification must use YAML syntax to be rendered in the generated website.
  Literal JSON is not supported.
* Ramler supports at most one level of nested subresources. Each top-level resource is turned into a
JAX-RS resource class. All methods of subresources of the given top-level resource will be turned
into methods of the same JAX-RS resource class.
  
= Java Code Generator

== Overview

Given a RAML specification, the Java code generator creates plain old Java objects (POJO) with getters
and setters for each structured type and a Java interface for each resource, with methods corresponding
to the HTTP methods defined in RAML.

RAML descriptions are converted to Javadoc comments.

== Maven Plugin

=== java Goal

[options="header"]
|=======================
| Parameter     | Type          | Meaning
| model         | String        | RAML specification file

| packageName   | String        | Fully qualified package name for generated Java sources. 
The generated classes will be located in subpackages `model` and `api`

| outputDir     | File          | Output directory for generated code. 
Default: `${project.build.directory}/generated-sources/ramler`

|=======================



=== java-test Goal  

[options="header"]
|=======================
| Parameter     | Type          | Meaning
| model         | String        | RAML specification file
| packageName   | String        | Fully qualified package name for generated Java sources. 
The generated classes will be located in subpackages `model` and `api`

| outputDir     | File          | Output directory for generated code. 
Default: `${project.build.directory}/generated-test-sources/ramler`
|=======================


// Return to normal title levels 
:leveloffset: 0
