= Ramler User Manual 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: OPS4J Ramler 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== Purpose

Ramler is a code and documentation generator for RESTful APIs defined by a 
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md[RAML 1.0 specification].

The RESTful API Modeling Language (http://www.raml.org[RAML]) is an open standard for API specifications.

Ramler supports a model-first strategy for designing, implementing and documenting a RESTful API.

Given a RAML specification, Ramler generates Java entity classes and resource interfaces compliant 
with JAX-RS 2.0.

Ramler also generates a static HTML 5 website with hyperlinked and searchable documentation directly
from a RAML specification. 

== Prerequisites

Ramler requires Java 8 and is best used with Maven 3.3.1 or higher. 

The HTML code generator is based on Node.js and npm, but this dependency is encapsulated by the
https://github.com/eirslett/frontend-maven-plugin[`frontend-maven-plugin`]. 

While Maven is not a strict requirement, it is the easiest way to use Ramler. If you prefer other
build tools, you will have to write some glue code to invoke Ramler APIs.

== Credits

* Ramler includes source code for some utility classes from 
https://github.com/mulesoft/raml-for-jax-rs[`raml-for-jax-rs`], but the Java code
generator is a largely independent implementation based on the 
https://github.com/raml-org/raml-java-parser[`raml-java-parser`].

* The HTML generator is a heavily modified copy of https://github.com/lord/slate[Slate], with all 
Ruby dependencies replaced by Java or JavaScript tools or libraries. 
HTML templates are based on http://www.trimou.org[Trimou].

= Working with Ramler

== Overview

Using Ramler, a RESTful API can be implemented in the following steps:

* Create a RAML 1.0 model of your API. It is recommended to use the 
https://atom.io/[Atom] editor with the 
http://apiworkbench.com/[API Workbench] plugin for this step. 

* Generate Java entity and API classes from the RAML model, either programmatically, or using the `ramler-maven-plugin`.

* Build a library from the generated classes and include this library in your Java application.

* Manually create JAX-RS resource classes implementing the interfaces generated by Ramler.

* Generate HTML documentation from the RAML model, either programmatically, or using the 
`ramler-maven-plugin`. You can use the default templates and styles or provide your own.

// Return to normal title levels 
:leveloffset: 0
