= Ramler User Manual 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: OPS4J Ramler 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== Purpose

Ramler is a code and documentation generator for RESTful APIs defined by a RAML 1.0 specification.

The RESTful API Modeling Language (RAML) is an open standard for API specifications.

Ramler supports a model-first strategy for designing, implementing and documenting a RESTful API.

Given a RAML specification, Ramler generates Java entity classes and resource interfaces compliant 
with JAX-RS 2.0.

Ramler also generates a static HTML 5 website with hyperlinked and searchable documentation directly
from a RAML specification. 


= Working with Ramler

Using Ramler, a RESTful API can be implemented in the following steps:

* Create a RAML 1.0 model of your API. It is recommended to use the Atom editor with the API Workbench plugin for this step. 

* Generate Java entity and API clasess from the RAML model, either programmatically, or using the 
`ramler-maven-plugin`.

* Build a library from the generated classes and include this library in your Java application.

* Manually create JAX-RS resource classes implementing the interfaces generated by Ramler.

* Generate HTML documentation from the RAML model, either programmatically, or using the 
`ramler-maven-plugin`. You can use the default templates and styles or provided your own.

// Return to normal title levels 
:leveloffset: 0
