#%RAML 1.0
title: Union Type
mediaType: application/json
types:
  City:
    properties:
      name: string
      population: integer
  Dog:
    properties:
      name: string
      furColour: string
  Favourite: City | Dog
