#%RAML 1.0
title: Generic Type
version: 0.1
mediaType: application/json
baseUri: http://localhost:8080
uses:
  g: ../ramler.raml 
annotationTypes:
  notes:  string[]
  note: string
types:
  Status:
    properties:
      code: integer
      httpStatus: integer
      requestId : string
      text : string
      success : boolean
  Result:
    (g.typeVars): [T]
    properties:
      result:
        (g.typeVar): T
        type: any
  ListResult:
    (g.typeVars):
      - T
    properties:
      result:
        (g.typeVar): T
        type: any[]
  Response: 
    (g.typeVars): [T]
    properties:
      data:
        type : Result
        (g.typeArgs):
        - T
      status: Status
      success: boolean
  Animal:
    (note): This is a note
    properties:
      species: string
      numLegs: integer
  AnimalResponse:
    type: Response
    (g.typeArgs): [Animal]
